default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: ()pgsql09
  host: localhost

development:
  database: inventorycontrol_dev
  <<: *default

test: &TEST
  database: inventorycontrol_test
  <<: *default

production:
  database: inventorycontrol
  <<: *default

cucumber:
  <<: *TEST
